In [7]:
import numpy as np

def swap_rows(matrix, row1, row2):
    """Intercambia dos filas en una matriz."""
    matrix[[row1, row2]] = matrix[[row2, row1]]
    return matrix

def multiply_row(matrix, row, scalar):
    """Mulitplica una fila por un escalar."""
    matrix[row] = matrix[row] * scalar
    return matrix

def add_multiple_row(matrix, row1, row2, scalar):
    """Suma un múltiplo de una fila a otra fila."""
    matrix[row2] = matrix[row2] + scalar * matrix[row1]
    return matrix

def gauss_elimination(matrix):
    """Realiza la eliminación de Gauss en una matriz."""
    rows, cols = matrix.shape
    for i in range(min(rows, cols - 1)):
        # Encontrar el pivote
        pivot_row = i
        for j in range(i + 1, rows):
            if abs(matrix[j, i]) > abs(matrix[pivot_row, i]):
                pivot_row = j
        swap_rows(matrix, i, pivot_row)

        # Hacer el pivote 1
        if matrix[i, i] != 0:
            multiply_row(matrix, i, 1 / matrix[i, i])

        # Hacer ceros debajo del pivote
        for j in range(i + 1, rows):
            add_multiple_row(matrix, i, j, -matrix[j, i])
    return matrix

def gauss_jordan_elimination(matrix):
    """Realiza la eliminación de Gauss-Jordan en una matriz."""
    matrix = gauss_elimination(matrix)
    rows, cols = matrix.shape
    for i in range(min(rows, cols - 1) - 1, -1, -1):
        # Hacer ceros encima del pivote
        for j in range(i - 1, -1, -1):
            add_multiple_row(matrix, i, j, -matrix[j, i])
    return matrix

def solve_system(matrix):
    """Resuelve un sistema de ecuaciones lineales a partir de una matriz en forma escalonada reducida por filas."""
    rows, cols = matrix.shape
    if rows < cols - 1:
        return "El sistema tiene infinitas soluciones o no tiene solución única."

    solutions = []
    for i in range(rows):
        # Verificar si la fila representa una inconsistencia (0 0 ... 0 | k, k!=0)
        if np.all(matrix[i, :-1] == 0) and matrix[i, -1] != 0:
            return "El sistema no tiene solución."
        # Extraer la solución para cada variable
        if i < cols - 1:
            solutions.append(matrix[i, -1])
    return solutions

# Ejemplo de uso con entrada del usuario:
matrix_input = get_matrix_input()
print("\nMatriz ingresada:")
display(matrix_input)

matrix_gauss = np.copy(matrix_input)
matrix_gauss = gauss_elimination(matrix_gauss)
print("\nMatriz después de la eliminación de Gauss:")
display(matrix_gauss)

matrix_gauss_jordan = np.copy(matrix_input)
matrix_gauss_jordan = gauss_jordan_elimination(matrix_gauss_jordan)
print("\nMatriz después de la eliminación de Gauss-Jordan:")
display(matrix_gauss_jordan)

solution = solve_system(matrix_gauss_jordan)
print("\nSolución del sistema:")
display(solution)

Ingresa el número de filas de la matriz: 3
Ingresa el número de columnas (incluyendo la columna de términos independientes): 4
Ingresa los elementos de la matriz fila por fila:
Fila 1 (separada por espacios): 2 1 1 3
Fila 2 (separada por espacios): 4 3 2 6
Fila 3 (separada por espacios): -2 5 4 7

Matriz ingresada:


array([[ 2.,  1.,  1.,  3.],
       [ 4.,  3.,  2.,  6.],
       [-2.,  5.,  4.,  7.]])


Matriz después de la eliminación de Gauss:


array([[1.        , 0.75      , 0.5       , 1.5       ],
       [0.        , 1.        , 0.76923077, 1.53846154],
       [0.        , 0.        , 1.        , 2.        ]])


Matriz después de la eliminación de Gauss-Jordan:


array([[ 1.00000000e+00,  0.00000000e+00, -2.77555756e-17,
         5.00000000e-01],
       [ 0.00000000e+00,  1.00000000e+00,  1.11022302e-16,
         2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.00000000e+00]])


Solución del sistema:


[np.float64(0.49999999999999994),
 np.float64(2.220446049250313e-16),
 np.float64(1.9999999999999998)]

In [5]:
def get_matrix_input():
    """Permite al usuario ingresar los datos de la matriz."""
    rows = int(input("Ingresa el número de filas de la matriz: "))
    cols = int(input("Ingresa el número de columnas (incluyendo la columna de términos independientes): "))

    matrix = np.zeros((rows, cols))

    print("Ingresa los elementos de la matriz fila por fila:")
    for i in range(rows):
        row_input = input(f"Fila {i + 1} (separada por espacios): ")
        elements = list(map(float, row_input.split()))
        if len(elements) != cols:
            print(f"Error: Debes ingresar {cols} elementos para la fila {i + 1}. Inténtalo de nuevo.")
            return get_matrix_input() # Reiniciar la entrada de la matriz
        matrix[i] = elements
    return matrix

# Ejemplo de uso de la función de entrada:
# matrix_input = get_matrix_input()
# print("\nMatriz ingresada:")
# display(matrix_input)